FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY src/ ./src/
COPY data/ ./data/
COPY tsconfig.json ./

RUN npm run build

ENV USERNAMES=${USERNAMES}
ENV TARGET_FILE=${TARGET_FILE}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV TARGET_BRANCH=${TARGET_BRANCH}
ENV CRON_SCHEDULE=${CRON_SCHEDULE}
ENV PACKAGE_REGEX=${PACKAGE_REGEX}
ENV LANGUAGE_REGEX=${LANGUAGE_REGEX}
ENV COMMIT_MESSAGE=${COMMIT_MESSAGE}
ENV REPOSITORY_OWNER=${REPOSITORY_OWNER}
ENV PROJECT_DELIMITER=${PROJECT_DELIMITER}
ENV TARGET_REPOSITORY=${TARGET_REPOSITORY}

CMD ["npm", "start"]